package com.giraffe.presentation.designsystem.icon

import com.giraffe.presentation.R

data class DueTone(
    val add: Int,
    val calendar: Int,
    val clock: Int,
    val colorSwitch: Int,
    val flame: Int,
    val folder: Int,
    val grid: Int,
    val headphone: Int,
    val heart: Int,
    val history: Int,
    val home: Int,
    val image: Int,
    val infoCircle: Int,
    val language: Int,
    val linkMinimalistic: Int,
    val login: Int,
    val logout: Int,
    val magicStick: Int,
    val moon: Int,
    val play: Int,
    val profile: Int,
    val rowVertical: Int,
    val search: Int,
    val star: Int,
    val station: Int,
    val timeLong: Int,
    val timeMedium: Int,
    val timeShort: Int,
    val trash: Int,
    val userSquare: Int,
    val videoLibrary: Int
)

val dueToneIcons = DueTone(
    add = R.drawable.due_tone_add,
    calendar = R.drawable.due_tone_calendar,
    clock = R.drawable.due_tone_clock,
    colorSwitch = R.drawable.due_tone_color_switch,
    flame = R.drawable.due_tone_flame,
    folder = R.drawable.due_tone_folder,
    grid = R.drawable.due_tone_grid,
    headphone = R.drawable.due_tone_headphone,
    heart = R.drawable.due_tone_heart,
    history = R.drawable.due_tone_history,
    home = R.drawable.due_tone_home,
    image = R.drawable.due_tone_image,
    infoCircle = R.drawable.due_tone_info_circle,
    language = R.drawable.due_tone_language,
    linkMinimalistic = R.drawable.due_tone_link_minimalistic,
    login = R.drawable.due_tone_login,
    logout = R.drawable.due_tone_logout,
    magicStick = R.drawable.due_tone_magic_stick,
    moon = R.drawable.due_tone_moon,
    play = R.drawable.due_tone_play,
    profile = R.drawable.due_tone_profile,
    rowVertical = R.drawable.due_tone_row_vertical,
    search = R.drawable.due_tone_search,
    star = R.drawable.due_tone_star,
    station = R.drawable.due_tone_station,
    timeLong = R.drawable.due_tone_time_long,
    timeMedium = R.drawable.due_tone_time_medium,
    timeShort = R.drawable.due_tone_time_short,
    trash = R.drawable.due_tone_trash,
    userSquare = R.drawable.due_tone_user_square,
    videoLibrary = R.drawable.due_tone_video_library
)
