package com.giraffe.media.utils

object DatabaseConstants {
    const val SERIES_TABLE = "SERIES"
    const val SERIES_GENRE_TABLE = "SERIES_GENRE"
    const val POPULAR_SERIES_TABLE = "POPULAR_SERIES"
    const val RECENTLY_RELEASED_SERIES_TABLE = "RECENTLY_RELEASED_SERIES"
    const val TOP_RATED_SERIES_TABLE = "TOP_RATED_SERIES"
    const val RECENT_VIEWED_SERIES_TABLE = "RECENT_VIEWED_SERIES"
    const val MATCHES_YOUR_VIBE_SERIES_TABLE = "MATCHES_YOUR_VIBE_SERIES"
    const val SEARCH_KEYWORD_TABLE = "SEARCH_KEYWORD"
    const val MOVIE_TABLE = "MOVIE"
    const val MOVIE_GENRE_TABLE = "MOVIE_GENRE"
    const val PERSONS_TABLE = "PERSONS"
    const val POPULAR_MOVIE_TABLE = "POPULAR_MOVIE"
    const val RECENTLY_RELEASED_MOVIE_TABLE = "RECENTLY_RELEASED_MOVIE"
    const val UPCOMING_MOVIE_TABLE = "UPCOMING_MOVIE"
    const val RECENTLY_VIEWED_MOVIE_TABLE = "RECENTLY_VIEWED_MOVIE"
    const val MATCHES_YOUR_VIBE_MOVIE_TABLE = "MATCHES_YOUR_VIBE_MOVIE"
}
