name: Deploy Debug to Firebase

on:
  pull_request:
    types: [ closed ]
    branches:
      - develop

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Building and distributing app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode and create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      # ✅ Add secrets.properties file before Gradle build
      - name: Create app/secrets.properties
        run: |
          mkdir -p app
          echo "API_KEY=${{ secrets.API_KEY }}" > app/secrets.properties
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> app/secrets.properties
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> app/secrets.properties

      - name: Execute Gradle command - assembleDebug
        run: ./gradlew assembleDebug

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIALS_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: "Automatic build from develop branch"